[package]
name = "durvald"
version = "0.1.0"
description = "A Tauri App"
authors = ["salguento"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "durvald_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
rfd = "0.14"
tauri-plugin-dialog = "2"
lofty = "0.22.4"
base64 = "0.22.1"
rusqlite = {version = "0.37.0", features = ["bundled"] }
tokio = {version = "1.48.0", features = ["full"] }
thiserror = "2.0.17"
kira = {version = "0.11.0", features = ["mp3", "ogg", "flac", "wav"] }
tokio-rusqlite = "0.7.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"
chrono = "0.4.42"
reqwest = { version = "0.13.1", features = ["json", "form"] }
md-5 = "0.10.6"
ring = "0.17.14"
once_cell = "1.21.3"
keyring = "3.6.3"
tauri-plugin-shell = "2.3.4"
sys-info = "0.9"
